# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache labsjdk download
        id: download
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: labsjdk-ce-15-jvmci-20.3-b01
          key: labsjdk-ce-15+36-jvmci-20.3-b01-linux-amd64
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          # restore-keys: # optional
      # Runs a set of commands using the runners shell
      - name: Download labs-jdk-adm64
        if: steps.download.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/graalvm/labs-openjdk-15/releases/download/jvmci-20.3-b01/labsjdk-ce-15+36-jvmci-20.3-b01-linux-amd64.tar.gz
          tar -xf labsjdk-ce-15+36-jvmci-20.3-b01-linux-amd64.tar.gz
      ## Add Cache here with git commit of mx 
      ## Add Cache here with git commit of graal ${{ steps.graal-commit.outputs.commit }}

      ## Clone Graal if needed
      - name: Get last Graal Commit
        id: graal-commit
        run: echo "::set-output name=commit::$(curl --silent https://api.github.com/repos/oracle/graal/commits/master | jq .sha -)" 
      - name: Cache git clone oracle/graal
        id: cache-git-clone-graal
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: graal
          key: graal-${{ steps.graal-commit.outputs.commit }}
      - name: Clone Graal if needed
        if: steps.cache-git-clone-graal.outputs.cache-hit != 'true'
        id: git-clone-graal
        run: |
          git clone https://github.com/oracle/graal      
      
      ## Git Clone GraalJS if needed
      - name: Get last GraalJS Commit
        id: graaljs-commit
        run: echo "::set-output name=commit::$(curl --silent https://api.github.com/repos/graalvm/graaljs/commits/master | jq .sha -)" 
      - name: Cache git clone graalvm/graaljs
        id: cache-git-clone-graaljs
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: graaljs
          key: graaljs-${{ steps.graaljs-commit.outputs.commit }}
      - name: Clone GraalJS if needed
        if: steps.cache-git-clone-graaljs.outputs.cache-hit != 'true'
        id: git-clone-graaljs
        run: |
          git clone https://github.com/graalvm/graaljs
          
      ## Git Clone MX if needed
      - name: Get last GraalVM MX Commit
        id: mx-commit
        run: echo "::set-output name=commit::$(curl --silent https://api.github.com/repos/graalvm/mx/commits/master | jq .sha -)"
      - name: Cache git clone graalvm/mx
        id: cache-git-clone-mx
        uses: actions/cache@v2.1.1
        with:
          path: mx
          key: mx-${{ steps.mx-commit.outputs.commit }}
      - name: Clone graalvm/mx if needed
        if: steps.cache-git-clone-mx.outputs.cache-hit != 'true'
        id: git-clone-mx
        run: |
          git clone https://github.com/graalvm/mx

      ## Git Clone graalpython if needed
      - name: Get last graalpython Commit
        id: graalpython-commit
        run: echo "::set-output name=commit::$(curl --silent https://api.github.com/repos/graalvm/graalpython/commits/master | jq .sha -)"
      - name: Cache git clone graalvm/graalpython
        id: cache-git-clone-graalpython
        uses: actions/cache@v2.1.1
        with:
          path: graalpython
          key: graalpython-${{ steps.graalpython-commit.outputs.commit }}
      - name: Clone graalvm/graalpython if needed
        if: steps.cache-git-clone-graalpython.outputs.cache-hit != 'true'
        id: git-clone-graalpython
        run: |
          git clone https://github.com/graalvm/graalpython

      ## Git Clone oracle/truffleruby if needed
      - name: Get last oracle/truffleruby Commit
        id: truffleruby-commit
        run: echo "::set-output name=commit::$(curl --silent https://api.github.com/repos/oracle/truffleruby/commits/master | jq .sha -)"
      - name: Cache git clone oracle/truffleruby
        id: cache-git-clone-truffleruby
        uses: actions/cache@v2.1.1
        with:
          path: truffleruby
          key: truffleruby-${{ steps.truffleruby-commit.outputs.commit }}
      - name: Clone oracle/truffleruby if needed
        if: steps.cache-git-clone-truffleruby.outputs.cache-hit != 'true'
        id: git-clone-truffleruby
        run: |
          git clone https://github.com/oracle/truffleruby
      #- name: Cache graal build
      #  id: cache-graal
      #  uses: actions/cache@v2.1.1
      #  with:
      #    path: |
      #      graal
      #      graaljs
      #      graalpython
      #      labsjdk-ce-15-jvmci-20.3-b01
      #      mx
      #      truffleruby
      #    key: graal1
      - name: Run a multi-line script
        if: steps.cache-graal.outputs.cache-hit != 'true'
        id: start-build
        run: |
          # LLVM needs cache 
          export JAVA_HOME=$PWD/labsjdk-ce-15-jvmci-20.3-b01
          export PATH=$JAVA_HOME/bin:$PATH
          echo $JAVA_HOME 
          export PATH=$PWD/mx:$PATH
          ls
          find . -iname mxbuild
          cd graal/vm
          #mx --env ce-complete graalvm-show
          mx --env ce sforceimports
          mx --env ce-no_native sforceimports
          cd ../..        
          #mx --env ce-no_native build
      - name: Cache build-ce
        id: cache-build-ce
        uses: actions/cache@v2.1.1
        with:
          path: |
            graal
            graaljs
            graalpython
            labsjdk-ce-15-jvmci-20.3-b01
            mx
            truffleruby
          key: cache-build-ce
      - name: Run real build ce
        if: steps.cache-build-ce.outputs.cache-hit != 'true'
        id: start-build-ce
        run: |
          export JAVA_HOME=$PWD/labsjdk-ce-15-jvmci-20.3-b01
          export PATH=$JAVA_HOME/bin:$PATH
          echo $JAVA_HOME 
          export PATH=$PWD/mx:$PATH
          cd graal/vm
          mx --env ce sforceimports
          mx --env ce build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            mx/mxbuild
            graaljs/graal-nodejs/mxbuild
            graaljs/graal-js/mxbuild
            graal/sdk/mxbuild
            graal/vm/mxbuild
            graal/compiler/mxbuild
            graal/substratevm/mxbuild
            graal/regex/mxbuild
            graal/tools/mxbuild
            graal/truffle/mxbuild
            graal/sulong/mxbuild
      - name: build ce artifacts
        id: build-ce-find-artifacts
        run: |
          find . -iname mxbuild
          
          
          
          
          
